### ISSUE TITLE
issue(docs): dartdoc documentation not completed

### ISSUE THREAD

**Issue by wzslr321** [wzslr321/artiver#14]
Documentation is still not completed - it requires to configure dartdoc - which unfortunately I am unable to test, because of my M1 Mac incompatibility with flutter image. It contains Dockerfile and commented out docker-compose config. I tried to make it work with my friend who helped me as tester, most of Dockerfile seems to work fine, but it can't properly find generated documentation and start server with dhttpd.

**Comment by akyunus** [comment]
I try to make it work. u need dart and flutter sdk on docker client. also u need to install all dependencies of the app with pub get. 
instaling all the sdk and other packages is it worth for it.

there are other options
1- push the generated docs to git repo. then u can serve the gerenated docs with a minimal webserver on docker. but It is not recommended to keep generateable content in git repo
2 - generate the docs on host then u can serve the gerenated docs with a minimal webserver on docker so u will need a simple script to generate docs and docker compose up. but this is contrary to the docker intended use.

**Comment by wzslr321** [comment]
Approach described first is the one that already is in the configuration. Flutter SDK includes Dart SDK. In  app's Dockerfile it runs `flutter pub get` and  `dartdoc` properly finishes and logs documentation successfully generated in `app/doc/api`, 
although **dhttpd**  can't find it, also docker's volumes don't seem to create anything. It might be possible to fix using `docker exec -it`and look for the docs path inside the docker itself, so it would be possible to specify as dhttpd argument.  But as you mentioned, installing all of this takes a while for a new contributor, so it may be not worth it on this stage, but consider situation when this project's front-end will finally grow and it'll be possible to dockerize flutter app itself and run it as web app. It will be inevitable then. 

approach with nginx is not recommended, but it may be a good enough solution for now. 

Last approach as you said, is contrary to the docker intended use, so I believe that shouldn't be used.
