### ISSUE TITLE
Kindly assign the following todo

### ISSUE THREAD

**Issue by sagar-monga** [wzslr321/artiver#6]
Hey! Can you assign the following card from ToDoList to me ? 

https://github.com/wzslr321/artiver/projects/1#card-63900742

**Comment by wzslr321** [comment]
Hey :--) 
I've just assigned it to you, we already have UI design of sign-in page on our Discord, check this out to create colors file correctly :-)

**Comment by sagar-monga** [comment]
Sure, I will check and update at the earliest :)

**Comment by wzslr321** [comment]
Everything clarified - closing.
